# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/bashnb',
                'doc_host': 'https://answerdotai.github.io',
                'git_url': 'https://github.com/answerdotai/bashnb',
                'lib_path': 'bashnb'},
  'syms': { 'bashnb.core': { 'bashnb.core.BashMagic': ('core.html#bashmagic', 'bashnb/core.py'),
                             'bashnb.core.BashMagic.__init__': ('core.html#bashmagic.__init__', 'bashnb/core.py'),
                             'bashnb.core.BashMagic.bash': ('core.html#bashmagic.bash', 'bashnb/core.py'),
                             'bashnb.core.create_ipython_config': ('core.html#create_ipython_config', 'bashnb/core.py'),
                             'bashnb.core.create_magic': ('core.html#create_magic', 'bashnb/core.py'),
                             'bashnb.core.load_ipython_extension': ('core.html#load_ipython_extension', 'bashnb/core.py')}}}
